### ISSUE TITLE
Ability to add multiple accounts

### ISSUE THREAD

**Issue by guyke01** [arjenbos/ha-postnl#18]
At this moment it is not possible to add a second account with the PostNL integration. When we add a second account no entities are added. When i check the logs there is an error that the sensors are already exist.

Is it possible to make something like a prefix or suffix from a name that is given in the setup of the integration?

**Comment by arjenbos** [comment]
I will add support for multiple accounts. 😄

**Comment by tonyhollaar** [comment]
@arjenbos thanks for the add-on for HA. Is there a timeline for support for multiple accounts?

**Comment by arjenbos** [comment]
I added multi account support and will release it as a beta release. Please test it 😄 .

**Comment by guyke01** [comment]
After a reboot the sensors will be switched or new sensors are being created on the 2 accounts.

Account 1
![image](https://github.com/user-attachments/assets/4ac6f313-9d49-4f6e-9e70-a5276cdfbcab)

Account 2
![image](https://github.com/user-attachments/assets/5728f344-8cfb-4566-8c49-b3592eb4233a)

After a second reboot the sensors switched or new sensors are created. Is it possible to add the name of the integration to the sensor so each account has it's own persistant name instead of the _1, _2, _3 ...

**Comment by tonyhollaar** [comment]
> I added multi account support and will release it as a beta release. Please test it 😄 .

Thank you for the code changes Arjen, I tested it for two accounts of PostNL and it works like a charm in Home Assistant.

Steps Taken:
1) I updated the version of PostNL in the HACS store in Home Assistant
2) I re-added the temporary browser extension here: https://github.com/arjenbos/ha-postnl-browser-extensions in Firefox.
3) In Home Assistant > Settings > Devices & Integrations > +Integration I re-added the PostNL integration for the second account.

**Comment by arjenbos** [comment]
> After a reboot the sensors will be switched or new sensors are being created on the 2 accounts.
> 
> Account 1 ![image](https://private-user-images.githubusercontent.com/59142637/371514261-4ac6f313-9d49-4f6e-9e70-a5276cdfbcab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NjI3ODgsIm5iZiI6MTcyNzc2MjQ4OCwicGF0aCI6Ii81OTE0MjYzNy8zNzE1MTQyNjEtNGFjNmYzMTMtOWQ0OS00ZjZlLTllNzAtYTUyNzZjZGZiY2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDA2MDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NDQzM2YwMmMyNjcyN2Y5ZmE0YmM5MWJiYzA0MmJiZTI3NmZhYTkxNGMzYzZhYjE2YmU5NDI0YTEzN2YzZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.692n6y6Lt1u2hKpTxJJyqFtZ6tFt_GrIqnRfU5i4BPk)
> 
> Account 2 ![image](https://private-user-images.githubusercontent.com/59142637/371514377-5728f344-8cfb-4566-8c49-b3592eb4233a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NjI3ODgsIm5iZiI6MTcyNzc2MjQ4OCwicGF0aCI6Ii81OTE0MjYzNy8zNzE1MTQzNzctNTcyOGYzNDQtOGNmYi00NTY2LThjNDktYjM1OTJlYjQyMzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDA2MDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MDgzODYxNmQ5OGY4ZDdkMjQ0NjI2NjM1YTI2YjE1NmU2ZDVmZjY1NDQxN2M1YTAzMmJjMWJmOWQ4MWNhNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lOQYBwlLmaNJj8Wq12ryA8zb3BoSG-2fYbghsxNglmw)
> 
> After a second reboot the sensors switched or new sensors are created. Is it possible to add the name of the integration to the sensor so each account has it's own persistant name instead of the _1, _2, _3 ...

The suffix are generated by HA. I would like to remove the _1, _2, etc as well, but I assume that people need to change their lovelace, automations, etc. That's why I didn't touch the name. I do not have a proper solutions right now.

**Comment by guyke01** [comment]
@arjenbos can you publish the 1.4.0 version? For now it's still beta.

**Comment by Geheim49** [comment]
That would be much appreciated! Would have saved me a lot of grey hairs.
