### ISSUE TITLE
Possibility to get less logging?

### ISSUE THREAD

**Issue by thoompje** [arjenbos/ha-postnl#20]
Hello,

Is there a possibility to set the integration a different log level? If I check my logs it's polling every few seconds and that comes directly in the log. Debug logging is disabled so that's not the case. How can I fix this? Many thanks.

Regards,

**Comment by arjenbos** [comment]
Hi @thoompje ,

Do you, maybe, have an override in the HA configuration? In the code I only use `debug` as a log level. See: https://www.home-assistant.io/integrations/logger/#log-levels.

**Comment by thoompje** [comment]
I think indeed it was my bad, in the configuration.yaml I had the logger set to "info"... Stupid. I close this threat, thanks!
