### ISSUE TITLE
Unexpected error fetching PostNL data: '3SQLFB9107139'

### ISSUE THREAD

**Issue by geert36** [arjenbos/ha-postnl#4]
```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.postnl.coordinator
Source: helpers/update_coordinator.py:290
Integration: PostNL (documentation, issues)
First occurred: 15:17:45 (1 occurrences)
Last logged: 15:17:45

Unexpected error fetching PostNL data: '3SQLFB9107139'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/postnl/coordinator.py", line 48, in _async_update_data
    colli = track_and_trace_details['colli'][shipment['barcode']]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: '3SQLFB9107139'

```

**Comment by geert36** [comment]
After updating to the latest version, I get this error:
`Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.postnl.coordinator
Source: helpers/update_coordinator.py:290
Integration: PostNL (documentation, issues)
First occurred: 18:00:21 (1 occurrences)
Last logged: 18:00:21

Unexpected error fetching PostNL data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/postnl/coordinator.py", line 58, in _async_update_data
    planned_date = colli.get('eta', None).get('start')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
`

**Comment by arjenbos** [comment]
Hi @geert36 , a couple of minutes ago I (hopefully) fixed this bug. When did you pull/downloaded the latest version?

**Comment by geert36** [comment]
Thanks @arjenbos, I will install the update. I updated this morning.

**Comment by arjenbos** [comment]
@geert36 please try again!

**Comment by geert36** [comment]
Yes, it is working now and one sensor (sensor.postnl_delivery) is created.
