### ISSUE TITLE
Naming (not an issue, just a question)

### ISSUE THREAD

**Issue by dennidoubles** [arjenbos/ha-postnl#9]
Thanks for bringing PostNL to live again in Home Assistant, very much appreciated!
I have a question. `sensor.postnl_distribution` has been added, which will show the packages delivered by ourselves, right?
But...when I add this sensor, it will show "delivered" two times, and also "enroute" :

![image](https://github.com/arjenbos/ha-postnl/assets/71798417/6416d03f-fff5-49e6-b5ad-6ded79ee6158)

Is it possible to rename the last "delivered" sensor, for example "delivered by me" ? Or is templating the only solution (if so)?

Thanks for looking into this!

**Comment by arjenbos** [comment]
Hi @dennidoubles ,

The integration creates two sensors which are used by the Lovelace. The sensor `postnl_distribution` contains the data of packages send by you.

Your question related to the Lovelace. I didn't build the Lovelace and I'm not maintaining the Lovelace. So, for now I can't help you with that; sorry! Nevertheless, I do agree with you and I may want to include a Lovelace in the integration.
